import React from "react";
import { api } from "../lib/api.js";
import { useFetchState } from "../lib/useFetchState.js";
import { SkeletonInsightList } from "../skeletons/Skeleton.jsx";
import ErrorState from "./ErrorState.jsx";

const severityClass = {
  info: "badge-info",
  watch: "badge-watch",
  critical: "badge-critical",
};

export default function InsightsPanel() {
  const { status, data, error, retry } = useFetchState(api.insights, []);

  return (
    <section className="panel">
      <div className="panel-header">
        <h2>AI Operational Notes</h2>
        {status === "success" && (
          <span
            className={`source-badge ${
              data.source === "gemini" ? "source-ai" : "source-deterministic"
            }`}
            title="Every number above is computed deterministically. This badge shows whether the narrative text was generated by Gemini (validated & entity-checked) or by the deterministic template fallback."
          >
            {data.source === "gemini" ? "Generated by Gemini" : "Deterministic summary"}
          </span>
        )}
      </div>

      {status === "loading" && <SkeletonInsightList count={3} />}
      {status === "error" && <ErrorState message={error} onRetry={retry} />}
      {status === "success" && (
        <>
          <ul className="insight-list">
            {data.items.map((item, i) => (
              <li key={i} className="insight-item">
                <span className={`badge ${severityClass[item.severity]}`}>
                  {item.severity}
                </span>
                <div>
                  <p className="insight-headline">{item.headline}</p>
                  <p className="insight-detail">{item.detail}</p>
                </div>
              </li>
            ))}
          </ul>
          <p className="disclaimer">{data.disclaimer}</p>
        </>
      )}
    </section>
  );
}
